### ISSUE TITLE
How can we auto import the edited files into TradeStation?

### ISSUE THREAD

**Issue by yhzhuo** [RiderTradingTools/easylanguage#2]
EasyLanguage code cannot run as standalone projects outside of TradeStation:
https://community.tradestation.com/Discussions/Topic.aspx?Topic_ID=222168

I see the supported file extensions are ".easylanguage", ".el", ".elf". Looks like these are not natively support file extensions of TradeStation:
https://help.tradestation.com/09_05/eng/tsdevhelp/el_editor/using_the_import_export_wizard.htm#

Then how can we import these files into TradeStation after editing them? Copy and paste is very error prone.

**Comment by RiderTradingTools** [comment]
Yes, that is a seriously frustrating limitation in TradeStation:  there is no option to open a text file in the TradeStation development environment.  

TradeStation compiles the EasyLanguage files to validate them, and that's done before saving (as ELD, ELS, or ELA) within TradeStation on your local computer.   Because of this, when you attempt File > Open, it is only looking for compiled files already stored within TradeStation.  And the import/export also looking for/working with compiled files (as ELD, ELS, or ELA).

Haven't found a way around this...

When using a 3rd party tool to edit (such as vsCode), Copy-Paste is your friend.  Best process to take flat file text and bring into the TradeStation editor is: 

- when in vsCode
- CTRL-A , CTRL-C  
- then click into TradeStation editor
- CTRL-A, CTRL-V 
- then recompile to check for any errors

You can use _AutoHotKey_ and write a helper script to do those steps for you, triggered on a custom keystroke.

**Comment by RiderTradingTools** [comment]
@yhzhuo  I have created a script with AutoHotKey (https://www.autohotkey.com/) if you're interested in trying it / using it.  

Basically the AutoHotKey script performs these actions:
(a) verifies matching filenames (between vsCode filename & TS Dev active tab)
(b) select-all from vsCode editor to copy all code in the editor
(c) switches focus to TradeStation Dev, and select-all to overwrite everything, then pastes the code.  
(d) runs the Verify command to ensure it's compiled / check for errors
(f) switches focus to the TradeStation program.

Lemme know if you're interested and I'll put it up here for you to test it out...

**Comment by RiderTradingTools** [comment]
No response.  Closing issue.  

If anyone else is interested in the AutoHotKey script please contact us.
